apiVersion: v1
kind: Service
metadata:
  name: {{ include "carts.fullname" . }}
  labels: {{- include "carts.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "carts.selectorLabels" . | nindent 4 }}
